function helpline(name, number, desc){
    return {
        name, number, desc
    }
} 

export default {
    Helpline : [
        helpline("Good2Talk", "1-866-925-5454", "Free, confidential support services for post-secondary students in Ontario ages 17-25."), 
        helpline("Hope For Wellness", "1-855-242-3310", "Offers immediate mental health counselling and crisis intervention to all Indigenous peoples across Canada. Available 24/7."),
        helpline("Oakville Distress Centre", "905-849-4541", "Distress Centre Halton provides telephone and online support to people to better cope with crisis, loneliness, and emotional stress. Also serves the Hamilton area."),
        helpline("Talk 4 Healing", "1-855-554-4325", "Indigenous women can get help, support and resources seven days a week, 24 hours a day, with services in 14 languages.")
    ],
    Action : "Take advantage of the provided mental health resources by reaching out to the suggested professionals and organizations. If you're in need of immediate support or counseling, don't hesitate to call the provided phone numbers for local mental health services. These resources are there to assist you in navigating your mental health journey, offering a listening ear, professional guidance, and valuable information. Remember that seeking help is a proactive step towards well-being, and these dedicated helplines can connect you with the support you need. Whether you're facing challenges, need someone to talk to, or are seeking professional advice, utilizing these resources can be a crucial part of your mental health care.",
    Tips : `There are a number of approaches you can try to deal with short and long term stress. \n\n- Identify your problems. What is causing your stress? It can be your job, a relationship or another source altogether. Is an unimportant surface problem masking a deeper one? Once you know what the problem is, you can do something about it. \n- Work on solutions. Start thinking about what you can do to relieve the problem. Take control over the issues you can manage. This might mean looking for another job, talking with a health professional about personal problems or a financial counsellor. Also ask yourself what will happen if you do nothing. Once you make some changes to deal with the issue, you will take pressure off yourself.\n- Talk about your problems. Friends, work colleagues and family members may not know you are having a hard time. If you talk to them about it, it may help in two ways. First of all, just by venting your feelings, you will relieve some stress. Secondly, they may suggest solutions to your problems. If you need to talk to someone outside your circle of family and friends, speak to your family physician or contact a mental health professional.\n- Learn about stress management. In addition to health professionals who specialize in stress, there are many helpful books, films, videos, courses and workshops available to help you learn stress management techniques.\n- Reduce tension. Physical activity is a great stress reducer. Walk, do some exercises or garden to relieve your stress. There are also relaxation exercises you can learn that will take the pressure off, such as deep breathing and stretching your whole body. Tension meditation and progressive relaxation are techniques that work for many people.\n- Take your mind off your problems. By reading, taking up a hobby or becoming involved in sports, you can give yourself a \`mental holiday\' from stress. It will also give you distance from your problems, so that they become easier to solve.\n- Try not to be too hard on yourself. Stress can cause lots of negative thinking. You may notice yourself saying things like "I can\'t, won\'t, should, must". Be realistic. Find realistic solutions you can achieve in steps that will bring success.`
};
